#!/system/bin/sh
##################################################
#
# eTHR ISP Android CLI Tool - Hadi Khoirudin, S. Kom.
# Custom ROM Version 1.4 - RC [24-09-2021]
# 
# Silahkan edit file ini untuk disesuaikan dengan HP yang akan digunakan.
#
# 1. Sambungkan eTHR melalui USB OTGnya
# *Untuk mengetahui TARGET_USB silahkan : 
# *Gunakan aplikasi Root Explorer
# *Buka file yang bernama fstab
# *Misal : fstab.qcom fstab.sc8920 dll
# *Temukan baris usb
# *Misal : /dev/block/platform/soc/7000000.ssusb/7000000.dwc3/xhci-hcd.0.auto*
# *Kemudian ubah menjadi : /dev/block/platform/soc/7000000.ssusb/7000000.dwc3/xhci-hcd.0.auto
#
# 2. Ubah TARGET_USB ini dengan target yang telah disesuaikan seperti di atas :
#
TARGET_USB=/dev/block/platform/soc/7000000.ssusb/7000000.dwc3/xhci-hcd.0.auto
#
#
#
# Set default sdcard location for read & save file
DIR_FILE=/sdcard

if [ -e "$DIR_FILE/eTHR" ] ; then 
OK=true
else
mkdir $DIR_FILE/eTHR
mkdir $DIR_FILE/eTHR/Dump

mkdir $DIR_FILE/eTHR/Partitions
mkdir $DIR_FILE/eTHR/Partitions/Write

mkdir $DIR_FILE/eTHR/Xiaomi
mkdir $DIR_FILE/eTHR/Xiaomi/UBL
mkdir $DIR_FILE/eTHR/Xiaomi/UBL_backup
mkdir $DIR_FILE/eTHR/Pinout

fi


# Set default mount location for data & system
DIR_DATA=/storage/eTHR/data

if [ -e "$DIR_DATA" ] ; then 
chmod 771 $DIR_DATA
chown system:system $DIR_DATA
else
mkdir /storage/eTHR
chmod 771 /storage/eTHR
chown system:system /storage/eTHR

mkdir $DIR_DATA
chmod 771 $DIR_DATA
chown system:system $DIR_DATA
fi

DIR_SYSTEM=/storage/eTHR/system

if [ -e "$DIR_SYSTEM" ] ; then 
chmod 771 $DIR_SYSTEM
chown system:system $DIR_SYSTEM
else
mkdir $DIR_SYSTEM
chmod 771 $DIR_SYSTEM
chown system:system $DIR_SYSTEM
fi

##################################################

function datetime() {
	NOW=$(date +"%d-%m-%Y_%H:%M")
}

function mount_userdata() {
if [ -e "$TARGET_USB/by-name/userdata" ] ; then
    echo "Mounting Data Partition"
    mount -t auto $TARGET_USB/by-name/userdata $DIR_DATA
    mount -o rw,remount $DIR_DATA
else
    echo " "
    echo -e $red " Error! Partition Userdata not found."
    echo "  Please check Direct ISP connection."$clear
    sleep 5
    SomethingWrong
fi
}

function mount_system() {
if [ -e "$TARGET_USB/by-name/system" ] ; then
    echo "Mounting System Partition"
    mount -t auto $TARGET_USB/by-name/system $DIR_SYSTEM
    mount -o rw,remount $DIR_SYSTEM
else
    echo " "
    echo -e $red " Error! Partition System not found." 
    echo " Please check Direct ISP connection..."$clear
    sleep 5
    SomethingWrong
fi
}


function identify_device() {
    echo "Reading information from device..."

if [ -e "$DIR_SYSTEM/build.prop" ] ; then
grep -i ro.product $DIR_SYSTEM/build.prop
sleep 8
    
    else
    mount_system
    if grep -qs $DIR_SYSTEM /proc/mounts; then
    grep -i ro.product $DIR_SYSTEM/build.prop
    sleep 8
    umount_system
    fi
fi
}

function mount_explore_userdata() {
    mount_userdata
    if grep -qs $DIR_DATA /proc/mounts; then
    cd /storage/eTHR/ && mc
    fi
}

function mount_explore_system() {
     mount_system
     if grep -qs $DIR_SYSTEM /proc/mounts; then
     cd /storage/eTHR/ && mc
     fi
}

function umount_userdata() {
    echo "Umount Data Partition"
	umount $DIR_DATA
}

function umount_system() {
    echo "Umount System Partition"
	umount $DIR_SYSTEM
}

function format_data() {
    echo "Formatting Data"
	mount_userdata
	sleep 4
	if [ -e "$DIR_DATA/app" ] ; then
	rm -rf $DIR_DATA/*
	mkdir $DIR_DATA/app
	echo "Success! Data Wiped."
	else
	if grep -qs $DIR_DATA /proc/mounts; then
	umount_userdata
	fi
	sleep 4
	mke2fs -t ext4 -F $TARGET_USB/by-name/userdata
	echo "Success! Data Formated."
	fi
	echo ""
	sleep 8
}

function remove_pin_gesture_lock() {
   echo "Removing PIN Gesture Lockscreen"
   
	mount_userdata
	
  if [ -e "$DIR_DATA/system" ] ; then
	sleep 1
	cd $DIR_DATA/system
	rm *.key
	cd /
	echo "PIN Gesture Lock Removed"
	echo ""
	umount_userdata
	sleep 5
	else
	echo -e $red "Error! Partition Data Encrypted."$clear
        echo -e $red "Operation Aborted..."$clear
  fi
	echo ""
	sleep 5
}

function remove_frp() {
    echo "Removing FRP / Google Account"
    echo " "
    if [ -e "$TARGET_USB/by-name/frp" ] ; then
    mke2fs -t ext4 $TARGET_USB/by-name/frp
    echo "Success!"
    sleep 5
    else
    echo -e $red "Error! This Device Has No FRP Partition."$clear
    echo -e $red "Operation Aborted..."$clear
    sleep 5
    fi
	echo ""
}

function write_single_partition() {
	echo ""
	echo "Write Single Partition to eMMC"
   echo "Select Partition :"
	
	select list1 in $(ls $TARGET_USB/by-name)
	do
	echo "Partition selected is ::" $list1
	if [ -e "$DIR_FILE/eTHR/Partitions/Write/$list1.img" ] ; then
	dd if=$DIR_FILE/eTHR/Partitions/Write/$list1.img of=$TARGET_USB/by-name/$list1
	sleep 8
	else
	echo -e $red "Error! Can't write partition."
	echo "Missing ::" $clear $DIR_FILE/eTHR/Partitions/Write/$list1.img
	sleep 8
	fi
	break
	done

	echo ""
}

function read_single_partition() {
	echo ""
	echo "Read Single Partition from eMMC"
    echo "Select Partition :"
	
	select list2 in $(ls $TARGET_USB/by-name)
	do
	echo "Partition selected is ::" $list2
	mkdir $DIR_FILE/eTHR/Partitions/$list2-$NOW
	dd if=$TARGET_USB/by-name/$list2 of=$DIR_FILE/eTHR/Partitions/$list2-$NOW/$list2.img
	sleep 8
	break
	done

	echo ""
}

function write_dump() {
	select list5 in $(ls $DIR_FILE/eTHR/Dump)
	do
	
	if [ -e "$DIR_FILE/eTHR/Dump/$list5/userarea.bin" ] ; then
	echo "Write Userarea Dump file to eMMC..."
	dd if=$DIR_FILE/eTHR/Dump/$list5/userarea.bin of=$TARGET_USB/sda
	echo " "
	echo "Success! Userarea Dump Writed to eMMC..."
	else
	echo -e $red "Error! Missing userarea.bin file."$clear
	fi
	
	sleep 10
	break
	done
}

function read_dump() {
   echo "Read & Saving Dump eMMC"
   echo " "
   echo "Please input name for saving Dump file : "
   read rdmp
   
	mkdir $DIR_FILE/eTHR/Dump/$rdmp-$NOW
	dd if=$TARGET_USB/sda of=$DIR_FILE/eTHR/Dump/$rdmp-$NOW/userarea.bin
	echo "Success!"
	echo "Saved to $DIR_FILE/eTHR/Dump/$rdmp-$NOW..."
	echo ""
	sleep 10
}

function ubl_xiaomi() {
	echo ""
	echo "Instan UBL Xiaomi"
    echo "Select Xiaomi CodeName / Product :"
	
	select list3 in $(ls $DIR_FILE/eTHR/Xiaomi/UBL)
	do
	echo "Device selected is ::" $list3
	if [ -e "$DIR_FILE/eTHR/Xiaomi/UBL/$list3" ] ; then
	
	mkdir $DIR_FILE/eTHR/Xiaomi/UBL_backup/$NOW
	dd if=$TARGET_USB/by-name/devinfo of=$DIR_FILE/eTHR/Xiaomi/UBL_backup/$NOW/$list3
	sleep 3
	
	dd if=$DIR_FILE/eTHR/Xiaomi/UBL/$list3 of=$TARGET_USB/by-name/devinfo
	sleep 8
	else
	echo -e $red "Error! Can't write devinfo."$clear
	sleep 8
	fi
	break
	done

	echo ""
}

function pinout_direct_isp() {
	echo ""

    echo "Select Device:"
	
	select list4 in $(ls $DIR_FILE/eTHR/Pinout)
	do
	termux-open --chooser $DIR_FILE/eTHR/Pinout/$list4
	sleep 8
	break
	done

	echo ""
}

function auto_unmount() {
if grep -qs $DIR_DATA /proc/mounts; then 
umount_userdata
fi

if grep -qs $DIR_SYSTEM /proc/mounts; then 
umount_system
fi
clear
}

function SomethingWrong() {
sleep 2
menu
}
##################################################
##
# Color  Variables
##
red='\e[31m'
green='\e[32m'
blue='\e[34m'
clear='\e[0m'

##
# Color Functions
##

ColorGreen(){
	echo -ne $green$1$clear
}
ColorBlue(){
	echo -ne $blue$1$clear
}

menu(){
datetime
clear
echo -ne "
  [eTHR - Direct ISP Android CLI eMMC Tool V1.4] 
 Created By : Hadi Khoirudin, S. Kom. [24/09/2021]
"

if [ -e "$TARGET_USB/sda" ] ; then

echo -ne "
Main Menu : 
$(ColorGreen '1)')  Identify Device
$(ColorGreen '2)')  Format / Wipe Data
$(ColorGreen '3)')  Remove PIN / Gesture Lockscreen
$(ColorGreen '4)')  Remove FRP / Google Account
$(ColorGreen '5)')  Mount & Explore System
$(ColorGreen '6)')  Mount & Explore Userdata
$(ColorGreen '7)')  Write Single Partition
$(ColorGreen '8)')  Read Single Partition
$(ColorGreen '9)')  Write Dump Userarea
$(ColorGreen '10)') Read Dump Userarea
$(ColorGreen '11)') Instant UBL Xiaomi
$(ColorGreen '12)') Pinout Direct ISP
$(ColorGreen '0)')  Exit

$(ColorBlue 'Choose Menu :') "
        read a
        case $a in
	        1) identify_device; menu ;;
	        2) format_data ; menu ;;
	        3) remove_pin_gesture_lock ; menu ;;
	        4) remove_frp ; menu ;;
	        5) mount_explore_system ; menu ;;
	        6) mount_explore_userdata ; menu ;;
	        7) write_single_partition ; menu ;;
	        8) read_single_partition ; menu ;;
	        9) write_dump ; menu ;;
	        10) read_dump ; menu ;;
	        11) ubl_xiaomi ; menu ;;
	        12) pinout_direct_isp ; menu ;;
		0) auto_unmount ; exit 0 ;;
		*) echo -e $red"Wrong input."$clear; SomethingWrong;;
        esac
else
echo -ne $blue" 
* Identify Device
* Format / Wipe Data
* Remove PIN / Gesture Lockscreen
* Remove FRP / Google Account
* Mount & Explore Partition System / Userdata
* Write & Read Single Partition
* Write & Read Dump Userarea
* Instant UBL Xiaomi
* Pinout Direct ISP
"

echo -ne $red"
Error : eTHR not detected!
Check USB OTG & eTHR connection then try again... 

"$clear

sleep 5
fi
}

# Call the menu function
menu
