#!/system/bin/sh
##################################################################################
#
# eTHR ISP Android CLI Tool - Hadi Khoirudin, S. Kom.
# Custom ROM Version 1.0 - RC [12-02-2021]
# 
# Silahkan edit file ini untuk disesuaikan dengan HP yang akan digunakan.
#
# 1. Sambungkan eTHR melalui USB OTGnya
# *Untuk mengetahui TARGET_USB silahkan : 
# *Gunakan aplikasi Root Explorer
# *Buka file yang bernama fstab
# *Misal : fstab.qcom fstab.sc8920 dll
# *Temukan baris usb
# *Misal : /devices/soc/78db000.usb/msm_hsusb_host*
# *Kemudian ubah menjadi : /dev/block/platform/soc/78db000.usb/msm_hsusb_host
#
# 2. Ubah TARGET_USB ini dengan target yang telah disesuaikan seperti di atas :
#
TARGET_USB=/dev/block/platform/soc/78db000.usb/msm_hsusb_host
#
#
#
# Set-Up Android
mount -o rw,remount /system && mount -o rw,remount rootfs

# Set default sdcard location for read & save file
DIR_FILE=/sdcard

if [ -e "$DIR_FILE/eTHR" ] ; then 
OK=true
else
mkdir $DIR_FILE/eTHR
mkdir $DIR_FILE/eTHR/Read
mkdir $DIR_FILE/eTHR/Read/Dump
mkdir $DIR_FILE/eTHR/Read/Partitions

mkdir $DIR_FILE/eTHR/Write
mkdir $DIR_FILE/eTHR/Write/Dump
mkdir $DIR_FILE/eTHR/Write/Partitions
fi

# Set default mount location for data & system
DIR_DATA=/storage/data

if [ -e "$DIR_DATA" ] ; then 
chmod 771 $DIR_DATA
chown system:system $DIR_DATA
else
mkdir $DIR_DATA
chmod 771 $DIR_DATA
chown system:system $DIR_DATA
fi

DIR_SYSTEM=/storage/system

if [ -e "$DIR_SYSTEM" ] ; then 
chmod 771 $DIR_SYSTEM
chown system:system $DIR_SYSTEM
else
mkdir $DIR_SYSTEM
chmod 771 $DIR_SYSTEM
chown system:system $DIR_SYSTEM
fi

##################################################################################

function datetime() {
	NOW=$(date +"%d-%m-%Y_%H%M")
}

function mount_data() {
    echo "Mounting Data Partition"
    mount -t auto $TARGET_USB/by-name/userdata $DIR_DATA
    mount -o rw,remount $DIR_DATA
    echo "Data mounted on $DIR_DATA"
    echo ""
    sleep 5
}

function mount_system() {
    echo "Mounting System Partition"
    mount -t auto $TARGET_USB/by-name/system $DIR_SYSTEM
    mount -o rw,remount $DIR_SYSTEM
    echo "System mounted on $DIR_SYSTEM"
    echo ""
    sleep 5
}

function umount_data() {
    echo "Umount Data Partition"
	umount $DIR_DATA
}

function umount_system() {
    echo "Umount System Partition"
	umount $DIR_SYSTEM
}

function format_data() {
    echo "Formatting Data"
	mount_data
	sleep 4
	if [ -e "$DIR_DATA/app" ] ; then
	rm -rf $DIR_DATA/*
	mkdir $DIR_DATA/app
	echo "Success!"
	echo "Data Wiped"
	else
	auto_unmount
	sleep 4
	mke2fs -t ext4 -F $TARGET_USB/by-name/userdata
	echo "Success!"
	echo "Data Formated"
	fi
	echo ""
	sleep 8
}

function remove_pin_gesture_lock() {
    echo "Removing PIN Gesture Lockscreen"
	mount -t auto $TARGET_USB/by-name/userdata $DIR_DATA
  if [ -e "$DIR_DATA/system" ] ; then
	sleep 1
	cd $DIR_DATA/system
	rm *.key
	cd /
	echo "PIN Gesture Lock Removed"
	echo ""
	sleep 5
	else
	echo "Error!"
	echo "Partition Data Encrypted"
        echo "Operation Aborted..."
  fi
	echo ""
	sleep 5
}

function remove_frp() {
    echo "Removing FRP / Google Account"
    echo " "
    if [ -e "$TARGET_USB/by-name/frp" ] ; then
    mke2fs -t ext4 $TARGET_USB/by-name/frp
    echo "Success!"
    sleep 5
    else
    echo "Error!"
    echo "This Device Has No FRP Partition!"
    echo "Operation Aborted..."
    sleep 5
    fi
	echo ""
}

function write_single_partition() {
	echo ""
	echo "Write Single Partition to eMMC"
    echo "Select Partition :"
	
	select list1 in $(ls $TARGET_USB/by-name)
	do
	echo "Partition selected is ::" $list1
	if [ -e "$DIR_FILE/eTHR/Write/Partitions/$list1.img" ] ; then
	dd if=$DIR_FILE/eTHR/Write/Partitions/$list1.img of=$TARGET_USB/by-name/$list1
	sleep 8
	else
	echo "Error!"
	echo "Missing ::" $DIR_FILE/eTHR/Write/Partitions/$list1.img
	sleep 8
	fi
	break
	done

	echo ""
}

function read_single_partition() {
	echo ""
	echo "Read Single Partition from eMMC"
    echo "Select Partition :"
	
	select list2 in $(ls $TARGET_USB/by-name)
	do
	echo "Partition selected is ::" $list2
	mkdir $DIR_FILE/eTHR/Read/Partitions/$NOW
	dd if=$TARGET_USB/by-name/$list2 of=$DIR_FILE/eTHR/Read/Partitions/$NOW/$list2.img
	sleep 8
	break
	done

	echo ""
}

function write_dump() {
    echo "Write Dump file to eMMC"
	dd if=$DIR_FILE/eTHR/Write/Dump/userarea.bin of=$TARGET_USB/sda
	echo "Success!"
	echo "Writed to eMMC..."
	echo ""
	sleep 10
}

function read_dump() {
    echo "Read & Saving Dump eMMC"
	mkdir $DIR_FILE/eTHR/Read/Dump/$NOW
	dd if=$TARGET_USB/sda of=$DIR_FILE/eTHR/Read/Dump/$NOW/userarea.bin
	echo "Success!"
	echo "Saved to $DIR_FILE/eTHR/Read/Dump..."
	echo ""
	sleep 10
}

function auto_unmount() {
if grep -qs $DIR_DATA /proc/mounts; then 
umount_data
fi

if grep -qs $DIR_SYSTEM /proc/mounts; then 
umount_system
fi
clear
}

function WrongCommand() {
sleep 2
menu
}
##################################################################################
##
# Color  Variables
##
green='\e[32m'
blue='\e[34m'
clear='\e[0m'

##
# Color Functions
##

ColorGreen(){
	echo -ne $green$1$clear
}
ColorBlue(){
	echo -ne $blue$1$clear
}

menu(){
datetime
clear
echo -ne "
eTHR Direct ISP Android CLI eMMC Tool [12/02/2021]
- Created By : Hadi Khoirudin, S. Kom

* Format / Wipe Data
* Mount Unencrypted Partition
* Only Remove PIN / Gesture Lockscreen
* Only Remove FRP / Google Account
* Write & Read Single Partition
* Write & Read Dump eMMC / eMCP
"

if [ -e "$TARGET_USB/sda" ] ; then
echo -ne "
Main Menu : 
$(ColorGreen '1)') Format / Wipe Data
$(ColorGreen '2)') Mount Data
$(ColorGreen '3)') Mount System
$(ColorGreen '4)') Remove PIN / Gesture Lockscreen
$(ColorGreen '5)') Remove FRP / Google Account
$(ColorGreen '6)') Write Single Partition
$(ColorGreen '7)') Read Single Partition
$(ColorGreen '8)') Write Dump User Area
$(ColorGreen '9)') Read Dump User Area
$(ColorGreen '0)') Exit
$(ColorBlue 'Choose an option:') "
        read a
        case $a in
	        1) format_data ; menu ;;
	        2) mount_data ; menu ;;
	        3) mount_system ; menu ;;
	        4) remove_pin_gesture_lock ; menu ;;
	        5) remove_frp ; menu ;;
	        6) write_single_partition ; menu ;;
	        7) read_single_partition ; menu ;;
	        8) write_dump ; menu ;;
	        9) read_dump ; menu ;;
		0) auto_unmount ; exit 0 ;;
		*) echo -e $red"Wrong option."$clear; WrongCommand;;
        esac
else
echo -ne "
Error : eMMC null / not detected!
Check USB OTG & eTHR connection then try again... 

"
sleep 5
fi
}

# Call the menu function
menu
